name: DropboxBackUp
author: [alvin0319, skymin]
main: alvin0319\DropboxBackUp\DropboxBackUp
version: 2.0.0
api: 4.0.0

commands:
  db:
    description: Starting backup on Dropbox
    permission: dropbox.cmd

permissions:
  dropbox.cmd:
    default: op
